name: My YourTomo cat

on:
  schedule:
    - cron: '23 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prsdx/github-pet@v1
        with:
          username: soniyakuchekar71
          timezone-offset-minutes: "330"
